### ISSUE TITLE
Unable to upload a snps

### ISSUE THREAD

**Issue by moedarrah** [Clinical-Genomics/genotype-api#19]
When testing the SNPs upload in Swagger I'm getting (Internal Server Error) I tried to delete or read the uploaded SNPs but it's empty so no SNP has been uploaded.

Error: response status is 500
--
![Screen Shot 2022-02-03 at 10 04 09](https://user-images.githubusercontent.com/41540288/152312208-e5806ac4-9988-4203-9d01-d1f232d18a70.png)

**Comment by Mropat** [comment]
```
Feb 03 09:56:51 cg-vm1.scilifelab.se podman[1020207]: 130.237.250.4:0 - "POST /snps/ HTTP/1.0" 500
Feb 03 09:56:51 cg-vm1.scilifelab.se podman[1020207]: [2022-02-03 08:56:51 +0000] [5] [ERROR] Exception in ASGI application
Feb 03 09:56:51 cg-vm1.scilifelab.se podman[1020207]: Traceback (most recent call last):
Feb 03 09:56:51 cg-vm1.scilifelab.se podman[1020207]:   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 378, in run_asgi
Feb 03 09:56:51 cg-vm1.scilifelab.se podman[1020207]:     result = await app(self.scope, self.receive, self.send)
Feb 03 09:56:51 cg-vm1.scilifelab.se podman[1020207]:   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
Feb 03 09:56:51 cg-vm1.scilifelab.se podman[1020207]:     return await self.app(scope, receive, send)
Feb 03 09:56:51 cg-vm1.scilifelab.se podman[1020207]:   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 212, in __call__
Feb 03 09:56:51 cg-vm1.scilifelab.se podman[1020207]:     await super().__call__(scope, receive, send)
Feb 03 09:56:51 cg-vm1.scilifelab.se podman[1020207]:   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
Feb 03 09:56:51 cg-vm1.scilifelab.se podman[1020207]:     await self.middleware_stack(scope, receive, send)
Feb 03 09:56:51 cg-vm1.scilifelab.se podman[1020207]:   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 181, in __call__
Feb 03 09:56:51 cg-vm1.scilifelab.se podman[1020207]:     raise exc
Feb 03 09:56:51 cg-vm1.scilifelab.se podman[1020207]:   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 159, in __call__
Feb 03 09:56:51 cg-vm1.scilifelab.se podman[1020207]:     await self.app(scope, receive, _send)
Feb 03 09:56:51 cg-vm1.scilifelab.se podman[1020207]:   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in __call__
Feb 03 09:56:51 cg-vm1.scilifelab.se podman[1020207]:     await self.simple_response(scope, receive, send, request_headers=headers)
Feb 03 09:56:51 cg-vm1.scilifelab.se podman[1020207]:   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response
Feb 03 09:56:51 cg-vm1.scilifelab.se podman[1020207]:     await self.app(scope, receive, send)
Feb 03 09:56:51 cg-vm1.scilifelab.se podman[1020207]:   File "/usr/local/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
Feb 03 09:56:51 cg-vm1.scilifelab.se podman[1020207]:     raise exc
Feb 03 09:56:51 cg-vm1.scilifelab.se podman[1020207]:   File "/usr/local/lib/python3.10/site-packages/starlette/exceptions.py", line 71, in __call__
Feb 03 09:56:51 cg-vm1.scilifelab.se podman[1020207]:     await self.app(scope, receive, sender)
Feb 03 09:56:51 cg-vm1.scilifelab.se podman[1020207]:   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 656, in __call__
Feb 03 09:56:51 cg-vm1.scilifelab.se podman[1020207]:     await route.handle(scope, receive, send)
Feb 03 09:56:51 cg-vm1.scilifelab.se podman[1020207]:   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 259, in handle
Feb 03 09:56:51 cg-vm1.scilifelab.se podman[1020207]:     await self.app(scope, receive, send)
Feb 03 09:56:51 cg-vm1.scilifelab.se podman[1020207]:   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 61, in app
Feb 03 09:56:51 cg-vm1.scilifelab.se podman[1020207]:     response = await func(request)
Feb 03 09:56:51 cg-vm1.scilifelab.se conmon[1020266]: [71B blob data]
Feb 03 09:56:51 cg-vm1.scilifelab.se podman[1020207]:   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 226, in app
Feb 03 09:56:51 cg-vm1.scilifelab.se podman[1020207]:     raw_response = await run_endpoint_function(
Feb 03 09:56:51 cg-vm1.scilifelab.se podman[1020207]:   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
Feb 03 09:56:51 cg-vm1.scilifelab.se podman[1020207]:     return await run_in_threadpool(dependant.call, **values)
Feb 03 09:56:51 cg-vm1.scilifelab.se podman[1020207]:   File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
Feb 03 09:56:51 cg-vm1.scilifelab.se podman[1020207]:     return await anyio.to_thread.run_sync(func, *args)
Feb 03 09:56:51 cg-vm1.scilifelab.se podman[1020207]:   File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 28, in run_sync
Feb 03 09:56:51 cg-vm1.scilifelab.se podman[1020207]:     return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
Feb 03 09:56:51 cg-vm1.scilifelab.se podman[1020207]:   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
Feb 03 09:56:51 cg-vm1.scilifelab.se podman[1020207]:     return await future
Feb 03 09:56:51 cg-vm1.scilifelab.se podman[1020207]:   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 754, in run
Feb 03 09:56:51 cg-vm1.scilifelab.se podman[1020207]:     result = context.run(func, *args)
Feb 03 09:56:51 cg-vm1.scilifelab.se podman[1020207]:   File "/home/worker/app/genotype_api/api/endpoints/snps.py", line 34, in upload_snps
Feb 03 09:56:51 cg-vm1.scilifelab.se podman[1020207]:     content = snps_file.decode()
Feb 03 09:56:51 cg-vm1.scilifelab.se podman[1020207]: UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8e in position 16: invalid start byte

```

**Comment by moedarrah** [comment]
I can upload locally, it's just that the swagger does not work and I need it as a reference to make sure that the upload is working as it should

**Comment by moedarrah** [comment]
Upload is working both locally and in Swagger, The test file was wrong!
